#!/usr/bin/env bash
#
# Generates the breakout-v<version> tag from an existing v<version> tag.
#
# The breakout variant is no longer a hand-maintained branch: it is the SAME
# code as the main tag, with exactly two deterministic changes applied by this
# script:
#   1. the self-referencing `bbb-breakout-sdk` dependency is stripped from
#      package.json / package-lock.json (a breakout cannot open another
#      breakout, and keeping the dep would make npm install recurse);
#   2. src/screens/inside-breakout-room-screen/sdk-loader.js is replaced by
#      sdk-loader.breakout.js, so the screen renders nothing instead of
#      importing the missing package.
#
# Everything else (which features show up inside a breakout) is decided at
# RUNTIME via the `isBreakout` prop / BreakoutInstanceProvider and the
# server-side `meeting.isBreakout` flag — see src/hooks/use-breakout-instance.js.
#
# Release flow:
#   1. bump package.json version to X.Y.Z and point the bbb-breakout-sdk dep
#      at #breakout-vX.Y.Z (the tag this script will create);
#   2. tag vX.Y.Z as usual;
#   3. ./scripts/make-breakout-tag.sh X.Y.Z
#   4. git push origin vX.Y.Z breakout-vX.Y.Z
#
# Usage: ./scripts/make-breakout-tag.sh <version> [--push]
#   <version>  version without prefix, e.g. 0.24.0 (tag v0.24.0 must exist)
#   --push     push the generated tag to origin when done

set -euo pipefail

VERSION="${1:?usage: $0 <version> [--push]}"
PUSH="${2:-}"
MAIN_TAG="v${VERSION}"
BREAKOUT_TAG="breakout-v${VERSION}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
WORKTREE="$(mktemp -d /tmp/bbb-breakout-tag.XXXXXX)"
LOADER_DIR="src/screens/inside-breakout-room-screen"

cleanup() {
  git -C "$REPO_ROOT" worktree remove --force "$WORKTREE" 2>/dev/null || true
  rm -rf "$WORKTREE"
}
trap cleanup EXIT

if ! git -C "$REPO_ROOT" rev-parse -q --verify "refs/tags/${MAIN_TAG}" >/dev/null; then
  echo "error: tag ${MAIN_TAG} not found — create the main release tag first" >&2
  exit 1
fi

if git -C "$REPO_ROOT" rev-parse -q --verify "refs/tags/${BREAKOUT_TAG}" >/dev/null; then
  echo "error: tag ${BREAKOUT_TAG} already exists" >&2
  exit 1
fi

echo "==> creating worktree at ${MAIN_TAG}"
git -C "$REPO_ROOT" worktree add --detach "$WORKTREE" "$MAIN_TAG"

cd "$WORKTREE"

echo "==> stripping bbb-breakout-sdk dependency"
npm pkg delete dependencies.bbb-breakout-sdk
# Rewrites package-lock.json without touching node_modules or the network
# beyond registry metadata; .npmrc (legacy-peer-deps) is picked up from the tree.
npm install --package-lock-only --ignore-scripts

echo "==> installing breakout sdk-loader stub"
if [ ! -f "${LOADER_DIR}/sdk-loader.breakout.js" ]; then
  echo "error: ${LOADER_DIR}/sdk-loader.breakout.js not found in ${MAIN_TAG}" >&2
  exit 1
fi
cp "${LOADER_DIR}/sdk-loader.breakout.js" "${LOADER_DIR}/sdk-loader.js"

echo "==> committing and tagging ${BREAKOUT_TAG}"
git add package.json package-lock.json "${LOADER_DIR}/sdk-loader.js"
git commit -m "chore(breakout): generate ${BREAKOUT_TAG} from ${MAIN_TAG}" \
  -m "Auto-generated by scripts/make-breakout-tag.sh — do not edit this tag by hand."
git tag "$BREAKOUT_TAG"

if [ "$PUSH" = "--push" ]; then
  echo "==> pushing ${BREAKOUT_TAG}"
  git push origin "$BREAKOUT_TAG"
else
  echo "==> done. Push it with: git push origin ${BREAKOUT_TAG}"
fi
